name: hubbahired
favicon: null
layout_spectrum: 0.06710717407986522
typography_spectrum: 0
title: HUBBA HIRED
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fafc'
    - '#323d42'
    - '#91baca'
    - '#61645f'
    - '#aa9077'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
