name: hubbahired
favicon: null
layout_spectrum: 0.06710717407986522
typography_spectrum: 0.6888603672850877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.8931643981486559
  saturation: 0.5
  rhythmicContrast: 0.9386874318588525
purpose: []
