name: HUBBA HIRED
favicon: null
layout_spectrum: 0.49702
typography_spectrum: 0.92245
title: HUBBA HIRED
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#474644'
    - '#00a65a'
    - '#b3a799'
    - '#000000'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
